name: Builds, tests & co

on:
  - push
  - pull_request

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout tree
        uses: actions/checkout@v4

      - name: Set-up Node.js
        uses: actions/setup-node@v4
        with:
          check-latest: true
          node-version-file: .nvmrc

      - run: corepack enable

      - run: yarn install --immutable

      - run: yarn lint

      - run: yarn build

      - run: yarn test --coverage

      - name: Generate code coverage report
        uses: coverallsapp/github-action@v2
        with:
          github-token: ${{ github.token }}
