name: Publish

on:
  release:
    types:
      - published

permissions: read-all

jobs:
  publish:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout tree
        uses: actions/checkout@v4

      - name: Set-up Node.js
        uses: actions/setup-node@v4
        with:
          check-latest: true
          node-version-file: .nvmrc

      - run: corepack enable

      - run: yarn install --immutable

      - run: yarn npm publish --tolerate-republish
        env:
          YARN_NPM_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
